#!/usr/bin/env ruby

# Copyright (c) 2013-2013, John Mettraux, jmettraux@gmail.com
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.
#
# Made in Japan.


lines = `git log --oneline --decorate --all`.split("\n")
history = lines.collect { |l| l.split.first }
head = lines.find { |l| l.match(/^[a-f0-9]+ \(HEAD[,\)]/) }.split.first
master = lines.find { |l| l.match(/^[a-f0-9]+ .*[\( ]master.*\)/) }.split.first
current = history.index(head)

cur = history[current]
pre = history[current + 1]
nex = history[current - 1]
ini = history.last

dir = ARGV[0]

if dir.nil?
  puts
  system('git log --graph --oneline --abbrev-commit --decorate --branches')
  puts
  exit(0)
end

target =
  case dir
    when '.' then cur
    when 'end', 'top' then 'master'
    when 'start' then ini
    when /^pre?v/ then pre
    when /^next?/ then nex
    else dir # tag or commit
  end

target = 'master' if target == master

raise "no commit for #{dir.inspect}" if target.nil?

system("git reset --hard --quiet HEAD")
system("git checkout --quiet #{target}")
puts
system("git log --oneline --abbrev-commit --decorate -1")

